### ISSUE TITLE
Application to create and manage containers

### ISSUE THREAD

**Issue by Phil997** [naimo84/node-red-contrib-dockerode#12]
Hello,
I want to design an application to create and manage containers. This should be done in Node-RED, because the Conatiner, which should be managed, are itself based on Node-RED. 
My question now is how to create a container with node-red-contrib-dockerode. Do the options to create have to be packed into the incoming payload of the nodes?

Up to now I have stored the function in a shell script. In principle I want to realize everything from the shell script in node-RED. The script I state with a number to enumerate the adapters.

> #!./bin/bash
$1
number=$1
containername=adapter_modbus$number
volumename=vol_adapter_modbus$number
porthost=$((55500 + $number))
adapterip=$((100 + $number))
docker volume create $volumename
docker create --net adapter_net --ip 172.20.0.$adapterip -p $porthost:1880 -v $volumename:/data --name $containername node-red_modus_image
docker start $containername

**Comment by naimo84** [comment]
Hi Phil,

as ethan (@ethanbrooks) writes here [ROADMAP.md](https://github.com/naimo84/node-red-contrib-dockerode/blob/master/ROADMAP.md) it's on the roadmap 😉 

But yes, I would expect the options in the payload. But also maybe in the config settings inside the node.

Greetings,
Benjamin

**Comment by chach17** [comment]
Hello Benjamin,

I am also trying to create a new container from Node-Red using your project.  It seems as though the functionality to create a container has been added since your last message.  I'm totally stumped on how to programmatically create the encounter from NodeRed.  Presently I have Container node set to "Create" and just prior I have a function node set to as follows:

msg.options = {Image: 'ubuntu', Cmd: ['/bin/bash']}
msg.action = "create"
return msg;

I get an error 500 indicating: 
"Error: (HTTP code 500) server error - json: cannot unmarshal string into Go value of type runconfig.ContainerConfigWrapper"

Can you please help explain the proper way to create a docker container?  Thank you so much for your time and for creating what looks to be a very cool Node-Red contribution.
